services:
  frontend:
    build:
      context: ./expensy_frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:8706
    container_name: expensy-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - expency

  backend:
    build:
      context: ./expensy_backend
      dockerfile: Dockerfile
    container_name: expensy-backend
    ports:
      - "8706:8706"
    environment:
      PORT: 8706
      DATABASE_URI: mongodb://root:example@mongo:27017
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: someredispassword
    depends_on:
      - mongo
      - redis
    networks:
      - expency

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-data:/data/db
    networks:
      - expency

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass someredispassword
    networks:
      - expency

volumes:
  mongo-data:

networks:
  expency:
    name: expency
