apiVersion: http.keda.sh/v1beta1
kind: InterceptorRoute
metadata:
  name: frontend
  namespace: staging
spec:
  target:
    service: frontend
    port: 3000
  rules:
    - hosts:
        - frontend.staging.20.85.194.20.sslip.io
  scalingMetric:
    concurrency:
      targetValue: 5