apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
<<<<<<< HEAD
- ../../base
- deployment.yaml
- ingress.yaml
- interceptorroute.yaml
- scaledobject.yaml
=======
  - ../base
  - deployment.yaml
  - ingress.yaml
  - interceptorroute.yaml
  - scaledobject.yaml
>>>>>>> f7d20ca (fix: kustomization.yaml, pull staging+main)
images:
- name: acr2poiclyh4krxy.azurecr.io/expensy-frontend
  newName: acr2poiclyh4krxy.azurecr.io/expensy-frontend
  newTag: 3668c96
