apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
resources:
  - ../../base
  - deployment.yaml
  - ingress.yaml
  - interceptorroute.yaml
  - scaledobject.yaml
images:
  - name: acr2poiclyh4krxy.azurecr.io/expensy-frontend
    newTag: staging-latest   # CI pipeline updates this value on every staging deploy
