apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: expensy-backend
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 8706
      targetPort: 8706
  type: ClusterIP
