apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
  - ../base
  - rollout.yaml
  - service-canary.yaml
  - analysis-template.yaml
  - ingress.yaml
  - interceptorroute.yaml
  - scaledobject.yaml
images:
  - name: acr2poiclyh4krxy.azurecr.io/expensy-backend
    newTag: latest   # CI pipeline updates this to <git-sha> on every production deploy
