apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
- ../base
- rollout.yaml
- service-canary.yaml
- analysis-template.yaml
- interceptorroute.yaml
- scaledobject.yaml

images:
- name: acr2poiclyh4krxy.azurecr.io/expensy-backend
  newName: acr2poiclyh4krxy.azurecr.io/expensy-backend
  newTag: c4f46be
