apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: expensy-backend
  namespace: monitoring
  labels:
    release: kube-prometheus-stack   # must match Prometheus operator selector
spec:
  namespaceSelector:
    matchNames:
      - staging
      - production
  selector:
    matchLabels: {}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s