---
# Step 2 — Namespaces
# All five namespaces required before any other resource is applied.
apiVersion: v1
kind: Namespace
metadata:
  name: staging
  labels:
    name: staging
    env: staging
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
    env: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: sonarqube
  labels:
    name: sonarqube
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
