apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-smtp-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-cluster-store
    kind: ClusterSecretStore
  target:
    name: alertmanager-smtp-secret
    creationPolicy: Owner
  data:
    - secretKey: smtp_auth_password
      remoteRef:
        key: alertmanager-smtp-password