apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cosmos-secret
  namespace: staging
  labels:
    app.kubernetes.io/part-of: expensy
    app.kubernetes.io/managed-by: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv-cluster-store
    kind: ClusterSecretStore
  target:
    name: cosmos-secret
    creationPolicy: Owner
    deletionPolicy: Retain          # keep the K8s Secret if ExternalSecret is deleted
    template:
      type: Opaque
      metadata:
        labels:
          app.kubernetes.io/part-of: expensy
  data:
    - secretKey: MONGODB_URI         # key inside the resulting K8s Secret
      remoteRef:
        key: cosmos-mongodb-connection-string   # Key Vault secret name
